# Generated by Django 4.2.2 on 2023-06-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admin'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
