# Generated by Django 4.2.2 on 2023-06-13 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 13, 21, 6, 44, 211125, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
